apiVersion: v1
kind: Secret
metadata:
  name: codecommit-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://git-codecommit.us-east-1.amazonaws.com/v1/repos/manifest-repo
  username: <codecommit-git-username>
  password: <codecommit-git-password>
